### ISSUE TITLE
PackageReference no longer works after uploading to NuGet

### ISSUE THREAD

**Issue by Drake53** [NuGet/Home#10247]
## Details about Problem

When I create a new package, I always add it to a local folder package source first.
To upload it to NuGet I normally upload it through the website, but since recently I have doing it using dotnet.exe nuget push:
```csharp
Process.Start("dotnet", $"nuget push \"{package}\" --api-key {ApiKey} --source {sourceString}");
```

I recently found out that for some reason, when my package is restored from my local folder package source, everything works correctly, but when it's restored from NuGet, visual studio/intellisense is unable to find the package's namespace and classes.

The .nupkg uploaded to NuGet is different from the original, because a file '.signature.p7s' is added. Everything else (when looking at the compressed/uncompressed sizes of the files in the .nupkg) appears to be the same.

I tested this with v0.1.0, v1.0.0, v1.1.0, and v1.1.1.
Only v0.1.0 does not have this problem (although it does also have the .signature file).
I think for v1.0.0 I still used the website to upload the package, so I don't think it's somehow caused by using dotnet.exe instead.

## Detailed repro steps so we can see the same problem

1. Create a new project with 'PackageReference Include="War3Net.IO.Mpq" Version="1.1.1"'

2. After the package is restored, 'using War3Net.IO.Mpq' gives error CS0246: type or namespace could not be found.

3. Delete the packages cache and restore the package (see attached file) from a local folder instead of from NuGet.

4. After the package is restored, the namespace is found and no longer gives an error.

From what I can tell, the signature somehow causes this issue, since that's the only difference between my local .nupkg file and the one uploaded on NuGet, but at the same time this signature file appears to exist in every version on NuGet, but not every version has this issue.

Does anyone know why this is happening and how this can be fixed? Thank you.

https://www.nuget.org/packages/War3Net.IO.Mpq

[War3Net.IO.Mpq.1.1.1.zip](https://github.com/NuGet/Home/files/5517411/War3Net.IO.Mpq.1.1.1.zip)

**Comment by Drake53** [comment]
I am no longer able to reproduce this issue after updating visual studio to 16.8.0
