### ISSUE TITLE
5.8 + 16.8 Cannot resolve transitive project dependencies when mixing PackageReference and packages.config

### ISSUE THREAD

**Issue by johnkors** [NuGet/Home#10326]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (5.8):
VS version (if appropriate): 16.8.x

Worked before? If so, with which NuGet version
Not entirely sure, but we did not experience an issue before installing 5.8 + 16.8.X
NuGet version (5.7):
VS version (if appropriate): 16.7.x

## Detailed repro steps so we can see the same problem

Given a project dependency chain::

```
TestProject (netcoreapp3.1) 
╚ MvcWebApplication (net461, packages.config old-style csproj) 
  ╚ DependencyA (netstandard2) 
    ╚ TransientProjectB (netstandard2)
```

The TestProject use classes from TransientProjectB directly in a test.

This fails with 
>D:\a\mixed-repro\mixed-repro\TestProject\UnitTest1.cs(3,7): error CS0246: The type or namespace name 'TransientProjectB' could not be found (are you missing a using directive or an assembly reference?) [D:\a\mixed-repro\mixed-repro\TestProject\TestProject.csproj]

The solution builds _fine_ in the IDE (Visual Studio 2019 16.8.X), but not via msbuild on the command line (and hence, not on our build servers).

It's easily enough fixed by adding a direct reference instead of keeping it transient, but was this breaking change on purpose? Why did it work in 16.7 whilst not in 16.8?

### Sample Project
Repo: https://github.com/icenorge/mixed-repro
Build script: https://github.com/icenorge/mixed-repro/blob/master/.github/workflows/MSBuild.yml
Failing build: https://github.com/icenorge/mixed-repro/runs/1453122655?check_suite_focus=true

**Comment by nkolev92** [comment]
Hey @johnkors, 

Thanks for the great repro. 

This is definitely an uncommon scenario and not one we'd recommend long term, but it is a bug. 

The *good news* is that we have a fix for that through https://github.com/NuGet/NuGet.Client/commit/a4c9d63bf942f1df1ba9486a87bad2e4b6888488. 
The *bad news* is that this is only in 5.9.0 right now. 

I will *add tests* to cover this scenario and ensure we don't regress it in the future.
We will consider patching this down level. 

cc @zivkan @aortiz-msft

**Comment by johnkors** [comment]
Thanks for looking into it!

>This is definitely an uncommon scenario and not one we'd recommend long term, but it is a bug.

To elaborate, this is not something we'd like either, but we are in the middle of migrating full framework applications to .NET Core / .NET 5. Migrating class libraries are easy, but larger MVC apps not so much. So for us, this is a very realistic dependency chain that we need to have working builds for as long as we have ongoing migrations. It will probably take us over the next year to be able to migrate apps.

**Comment by nkolev92** [comment]
Hey @johnkors 
If possible, we'd appreciate it you can help us confirm that your issue is addresed by testing out https://dist.nuget.org/win-x86-commandline/v5.9.0-preview.2/nuget.exe

**Comment by johnkors** [comment]
Looks good: https://github.com/icenorge/mixed-repro/pull/2/files
