### ISSUE TITLE
Nuget 2.8.6 commandline does not support -build on C# 6.0 syntax

### ISSUE THREAD

**Issue by LogikBlitz** [NuGet/Home#1107]
Building packages, using the ```-build``` param to let nuget build the code before creating a package worked fine before i started using the new syntax of C# 6.0

In this case the use of **string interpolation** https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#string-interpolation
but i suspect that the other new syntax candy introduced might also pose a problem as well.

Command:
```
nuget.exe pack C:\PATH_TO_PROJECT\foobar.csproj -Symbols -build -prop configuration=release  -includereferencedprojects -verbosity detailed
```

Error subtract
```
DataStore\IqlMacroDataStore.cs(74,41): error CS1056: Unexpected character '$'
DataStore\IqlMacroDataStore.cs(117,21): error CS1056: Unexpected character '$'
DataStore\IqlMacroDataStore.cs(122,21): error CS1056: Unexpected character '$'
Repositories\IqlMacroRepository.cs(15,59): error CS1056: Unexpected character '$'
```

At time of writing the version of nuget.exe was the latest that could be downloaded from https://docs.nuget.org/consume/installing-nuget

**Comment by yishaigalatzer** [comment]
Thanks for reporting it, this is likely to the fact that we are using an older version of msbuild that picks up the older C# tooling.

Note that we do have a newer command line available in beta form. Declared here - http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

and available for download from here - http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe

**Comment by LogikBlitz** [comment]
I can confirm that the latest beta 3.1.0.0  does indeed work with the -build parameter with C# 6 syntax.
Im closing this issue since it seems that the new MSBuild will be implemented in the - to be released- Nuget.exe 3.*

**Comment by yishaigalatzer** [comment]
Awesome! Thanks for verifying it.

**Comment by LogikBlitz** [comment]
And so im back with sad tidings.
Unfortunately my test had been run against a project that did not contain any C# 6 specific syntax.

I have now retried using a project that uses c# 6 specific syntax and i get the error.

```
 error CS1056: Unexpected character '$'
```

Nuget info
```
PS C:\> nuget
nuget Version: 3.1.0.0
```

I very sorry that i made this stupid test mistake :-1:

**Comment by yishaigalatzer** [comment]
No problems, we will take a look
