### ISSUE TITLE
Build in Visual Studio 2017 utterly fails

### ISSUE THREAD

**Issue by chris1248** [NuGet/Home#5117]
## Details about Problem

NuGet HEAD is da863e0eb0cdc7d4fc079a573ed2558f00836fcf

VS version (2017):

OS version (win10):

## Detailed repro steps so we can see the same problem

1. I pulled down the nuget client repo this morning and built the default branch `dev`. It built fine, but there were a ton of warnings btw (i.e. MSB3277).
2. Started up the solution file: `NuGet.sln` found in the root of the git repo
3. Selected `Nuget.Commandline` as the startup project
4. Selected F5 to debug it. 

RESULT:
Visual Studio (like always) wanted to rebuild everything, which failed right away with a **bazillion** compiler errors. Well actually 3118 errors and 42 warnings.

### Verbose Logs

```Error occurred while restoring NuGet packages: Object reference not set to an instance of an object.
1>------ Build started: Project: NuGet.Common, Configuration: Debug Any CPU ------
2>------ Build started: Project: NuGet.Versioning, Configuration: Debug Any CPU ------
3>------ Build started: Project: NuGet.Frameworks, Configuration: Debug Any CPU ------
2>Properties\AssemblyInfo.cs(6,12,6,24): error CS0246: The type or namespace name 'CLSCompliantAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>Properties\AssemblyInfo.cs(6,12,6,24): error CS0246: The type or namespace name 'CLSCompliant' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\me\AppData\Local\Temp\.NETStandard,Version=v1.0.AssemblyAttributes.cs(4,20,4,26): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
...
...
```

So is building any of the nuget projects in visual studio (for debugging) not supported?

**Comment by zhili1208** [comment]
it's supported in Visual studio, Did you follow those steps?

Steps to build NuGet client tools
Clone NuGet/NuGet.Client repository
git clone https://github.com/NuGet/NuGet.Client
Start PowerShell. CD into the cloned repository directory.
Run configuration script
.\configure.ps1
Build with
.\build.ps1 -SkipUnitTest
Or Build and Unit test with
.\build.ps1
Run all test-suites if inside Microsoft corpnet
.\runTests.ps1

**Comment by emgarten** [comment]
This may have been caused by a15fd847eb1a764db1cce17e1858f24c0421e0c0 try syncing to 471d02c54b1e2b6e8c20352da474cb7096dc87d4

**Comment by mishra14** [comment]
@chris1248 Can you please try with the latest commit on dev branch and let us know if you are still facing this problem.
